// Generated by ts-to-zod
import { z } from 'zod'

export const timestampSchema = z.date()

export const dataSchema = z.object({
  id: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
  data: z.string(),
})

export const userSchema = z.object({
  id: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
  name: z.string(),
  pwd: z.string(),
})

export const dbSchema = z.object({
  data: dataSchema,
  user: userSchema,
})
